### ISSUE TITLE
The Partner network in Israel (42501) is incorrectly identified

### ISSUE THREAD

**Issue by eladts** [bluelinepc/signalcheck#62]
**Describe the bug**
The Partner network in Israel (42501) is incorrectly identified. It is either misidentified as "Orange (4251)"  with an orange color bar while connected to LTE or as "Google Fi (4251)" while connected to NR NSA or 3G/2G. 

**To Reproduce**
I'm a Google Fi subscriber roaming in Israel on the [Partner](https://www.partner.co.il/) network.

**Expected behavior**
The carrier should be displayed as "Partner (42501)" and the color bar should be teal.

**Screenshots**
![Screenshot_20240820-215309](https://github.com/user-attachments/assets/af90e24a-ea29-4ff9-9470-5e12eb62b53d)
![Screenshot_20240820-215550](https://github.com/user-attachments/assets/2c0e69f9-1ab5-4928-b1e5-6115e36098bb)

**Device details**
 - Device: Pixel 8
 - Android version: 14
 - SignalCheck version: 4.841

**Additional context**
- The leading '0' is missing from the MNC. Android radio info screen shows the PLNM as '42501'.
- Partner  used the Orange branding until 2016, but since then it has used its own branding.

**Comment by eladts** [comment]
![Screenshot_20240825-160257](https://github.com/user-attachments/assets/b6aa2f4b-d091-473a-a585-8d3f4a6258f8)

Also, n78 is misidentified as n77.

**Comment by mikejeep** [comment]
Thanks for these reports! The dropped leading '0' already has a fix in testing. That is why your provider is being improperly identified and likely also why it is miscalculating your NR band. I hope to have the fix released soon; I will update this issue once that happens.

**Comment by mikejeep** [comment]
This should be resolved in the latest version (4.85), released on October 12. Please confirm if it has been fixed or if the issue persists.. thanks!

**Comment by eladts** [comment]
I'm back in the US, so I cannot see if the issue is fixed. I will test this next time I'm in Israel.

**Comment by mikejeep** [comment]
Ok, thank you -- I will close for now, please feel free to re-open if you experience the problem again.

**Comment by eladts** [comment]
I'm back visiting Israel and the bug is only partially fixed:

- Outdated network names are still shown: **42501** is shown as _Orange_, while the network is now called _Partner_. **42507** is shown as _Mirs Ltd_, while the current name is _HOT mobile_.
- When connected to 3G the network code is still missing the leading 0, so the network isn't detected. When connected to LTE or NR this issue is fixed.
- n78 is still mislabeled as n77.

@mikejeep Please reopen this bug.

**Device details**

Device: Pixel 8
Android version: 16
SignalCheck version: 4.86
